- hosts: all
  vars_files:
    - config/main.yml
  tasks:
    - name: generate_file_using_template
      template:
        src: templates/etc/haproxy.cfg.j2
        dest: /tmp/haproxy.cfg
        force: no