- hosts: all
  vars:
    variable_to_be_replaced: 'Vener'
    inline_variable: 'Guevarra'
  tasks:
    - name: generate_file_using_template
      template:
        src: templates/hello_world.j2
        dest: /tmp/hello_world.txt
        force: yes